config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :coaches
  resources :tournaments
  resources :players
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :matches
  has_many :players, through: :matches
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    tParams = params[:tournament]
    @tournament = Tournament.new(name: tParams[:name], venue: tParams[:venue], winner: Player.find_by(name: tParams[:winner]).id)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tournament_params
      params.require(:tournament).permit(:name, :venue, :winner)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% players_array = Player.all.map { |player| [player.name] }%>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_field :venue %>
  </div>

  <div class="field">
    <%= form.label :winner %>
    <%= form.select :winner, players_array %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Venue</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.venue %></td>
        <td><%= Player.find_by(id: tournament.winner).name %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @tournament.venue %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @tournament.winner %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>