config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :coaches
  resources :tournaments
  resources :players
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :player
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    coach_params[:player_id] = Player.find_by(name: coach_params[:player_id]).id
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coach_params
      params.require(:coach).permit!
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_with(model: coach, local: true) do |form| %>
  <% if coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<% players_array = Player.all.map { |player| [player.name] }%>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.select :player_id, players_array %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td><%= link_to 'Show', coach %></td>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coach', new_coach_path %>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coach.name %>
</p>

<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>