config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :coaches
  resources :tournaments
  resources :players
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :games
  has_many :players, through: :games
  belongs_to :tournament
  attr_accessor :firstPlayer
  attr_accessor :secondPlayer
  attr_accessor :thirdPlayer
  attr_accessor :fourthPlayer
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  # GET /matches
  # GET /matches.json

  def index
    @matches = Match.all
    @players = []
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    mParams = params[:match]
    begin
      @tournament = Tournament.find_by(id: Integer(Tournament.find_by(name: mParams["tournament_id"]).id))
    rescue err
      return
    end

    @match = Match.new("matchtype": mParams[:matchtype])
    @match.tournament = @tournament

    respond_to do |format|
      if @match.save
        if mParams[:matchtype] == "Singles"
          @players = [
            Player.find_by(name: mParams[:firstPlayer]),
            Player.find_by(name: mParams[:secondPlayer])
          ]
        else
          @players = [
            Player.find_by(name: mParams[:firstPlayer]),
            Player.find_by(name: mParams[:secondPlayer]),
            Player.find_by(name: mParams[:thirdPlayer]),
            Player.find_by(name: mParams[:fourthPlayer])
          ]
        end

        @match.players << @players

        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getPlayersString
    if @match.players
      str = "["
      @match.players do |player|
        str += player.name
        str += ","
      end
      str += "]"
    else
      return "No Players"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:matchtype, :tournament_id, :players)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :matchtype %>
    <%= form.select :matchtype, ["Singles", "Doubles"] %>
  </div>
  <% tournament_array = Tournament.all.map { |t| [t.name] }%>

  <div class="field">
    <%= form.label :tournament_id %>
    <%= form.select :tournament_id, tournament_array %>
  </div>

  <% players_array = Player.all.map { |player| [player.name] }%>
  <h2>Players </h2>
  <% if params[:matchtype] == "Singles" %>
      <div class="field">
        <%= form.select :firstPlayer, players_array %>
      </div>
      <div class="field">
        <%= form.select :secondPlayer, players_array %>
      </div>
  <% else %>
      <div class="field">
        <%= form.select :firstPlayer, players_array %>
      </div>
      <div class="field">
        <%= form.select :secondPlayer, players_array %>
      </div>
      <div class="field">
        <%= form.select :thirdPlayer, players_array %>
      </div>
      <div class="field">
        <%= form.select :fourthPlayer, players_array %>
      </div>
  <% end %>

  <h2>Create </h2>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td>ID: <%= match.id %></td>
        <td>Type: <%= match.matchtype %></td>
        <td>Players: [
          <% match.players.each do |player| %>
            <%= player.name %>,
          <% end %>
          ]
        </td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @match.matchtype %>
</p>
<!-- <p>
  <strong>Players:</strong>
  <%# <%= @match.players do |player| %> %>
</p> -->

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>